<?php
// Rebuild consolidated SQL entry files from the canonical database sources.
// Usage: php scripts/db/rebuild_consolidated_sql.php [project-root]

declare(strict_types=1);

$projectRoot = $argv[1] ?? dirname(__DIR__, 2);
$projectRoot = rtrim($projectRoot, DIRECTORY_SEPARATOR);
$dbDir = $projectRoot . DIRECTORY_SEPARATOR . 'database';
$migrationsDir = $dbDir . DIRECTORY_SEPARATOR . 'migrations';

$schemaFile = $dbDir . DIRECTORY_SEPARATOR . 'schema.sql';
$seedFile = $dbDir . DIRECTORY_SEPARATOR . 'seed_demo.sql';
$installFreshFile = $dbDir . DIRECTORY_SEPARATOR . 'install_fresh_latest.sql';
$installDemoFile = $dbDir . DIRECTORY_SEPARATOR . 'install_with_demo_seed.sql';
$updateBundleFile = $dbDir . DIRECTORY_SEPARATOR . 'update_latest_bundle.sql';

$required = [$schemaFile, $seedFile, $migrationsDir];
foreach ($required as $path) {
    if (!file_exists($path)) {
        fwrite(STDERR, "Missing required path: {$path}\n");
        exit(1);
    }
}

/**
 * @return list<string>
 */
function migrationFiles(string $dir): array
{
    $files = glob($dir . DIRECTORY_SEPARATOR . 'upgrade_v*.sql') ?: [];
    usort($files, static function (string $a, string $b): int {
        preg_match('/upgrade_v(\d+)\.sql$/', basename($a), $ma);
        preg_match('/upgrade_v(\d+)\.sql$/', basename($b), $mb);
        return ((int)($ma[1] ?? 0)) <=> ((int)($mb[1] ?? 0));
    });
    return array_values($files);
}

function readSql(string $path): string
{
    $data = file_get_contents($path);
    if ($data === false) {
        throw new RuntimeException("Unable to read {$path}");
    }
    return trim(str_replace(["\r\n", "\r"], "\n", $data));
}

function section(string $title, string $sql): string
{
    return "-- =============================================\n"
        . "-- {$title}\n"
        . "-- =============================================\n\n"
        . trim($sql)
        . "\n\n";
}

try {
    $schemaSql = readSql($schemaFile);
    $seedSql = readSql($seedFile);
    $migrationSql = '';
    foreach (migrationFiles($migrationsDir) as $file) {
        $migrationSql .= section('Migration: ' . basename($file), readSql($file));
    }

    $freshHeader = "-- Consolidated fresh install file\n"
        . "-- Generated by scripts/db/rebuild_consolidated_sql.php\n"
        . "-- Canonical source: database/schema.sql\n\n";
    file_put_contents($installFreshFile, $freshHeader . trim($schemaSql) . "\n");

    $demoHeader = "-- Consolidated fresh install with demo seed\n"
        . "-- Generated by scripts/db/rebuild_consolidated_sql.php\n"
        . "-- Canonical sources: database/schema.sql + database/seed_demo.sql\n\n";
    file_put_contents($installDemoFile,
        $demoHeader
        . section('Fresh schema', $schemaSql)
        . section('Demo seed', $seedSql)
    );

    $updateHeader = "-- Consolidated update bundle\n"
        . "-- Generated by scripts/db/rebuild_consolidated_sql.php\n"
        . "-- Canonical sources: database/migrations/upgrade_v*.sql\n"
        . "-- Back up your database before applying this file.\n\n";
    file_put_contents($updateBundleFile, $updateHeader . trim($migrationSql) . "\n");

    fwrite(STDOUT, "Rebuilt consolidated SQL files successfully.\n");
    fwrite(STDOUT, "- {$installFreshFile}\n- {$installDemoFile}\n- {$updateBundleFile}\n");
} catch (Throwable $e) {
    fwrite(STDERR, $e->getMessage() . "\n");
    exit(1);
}
