blank_issues_enabled: false
contact_links:
  - name: General discussion
    url: https://github.com/shreyanshjain1/Medicine_sales_reports/discussions
    about: Use discussions for open-ended questions or ideas.
