<?php
require_once __DIR__ . '/../init.php';
if (!can_run_setup()) { http_response_code(403); exit('Setup is disabled. Enable ALLOW_SETUP in config.php temporarily to use this page.'); }
$key = trim((string)($_GET['key'] ?? ''));
if ($key === '' || !hash_equals((string)SETUP_KEY, $key)) { http_response_code(403); exit('Invalid setup key.'); }
function q($sql){ global $mysqli; if(!$mysqli->query($sql)){ echo '<li style="color:#b91c1c">ERR: '.htmlspecialchars($mysqli->error).'</li>'; } else { echo '<li>'.htmlspecialchars($sql).'</li>'; } }
echo '<h1>Medicine Sales CRM — Setup</h1>';
echo '<p>Creating core tables only. Demo users are no longer auto-seeded.</p><ul>';
q("CREATE TABLE IF NOT EXISTS users ( id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(150) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role ENUM('manager','district_manager','employee') NOT NULL DEFAULT 'employee', district_manager_id INT NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX (district_manager_id), CONSTRAINT fk_users_district_manager FOREIGN KEY (district_manager_id) REFERENCES users(id) ON DELETE SET NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
q("CREATE TABLE IF NOT EXISTS reports ( id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, doctor_name VARCHAR(120) NOT NULL, doctor_email VARCHAR(150), purpose VARCHAR(200), medicine_name VARCHAR(200), hospital_name VARCHAR(200), visit_datetime DATETIME NOT NULL, summary TEXT, remarks TEXT, signature_path VARCHAR(255), status ENUM('pending','approved','needs_changes') NOT NULL DEFAULT 'pending', manager_comment TEXT, attachment_path VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX (user_id), INDEX (visit_datetime), INDEX(status), CONSTRAINT fk_rep_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
q("CREATE TABLE IF NOT EXISTS events ( id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, title VARCHAR(200) NOT NULL, city VARCHAR(120) DEFAULT NULL, doctor_id INT DEFAULT NULL, purpose VARCHAR(200) DEFAULT NULL, medicine_name VARCHAR(200) DEFAULT NULL, hospital_name VARCHAR(200) DEFAULT NULL, visit_datetime DATETIME DEFAULT NULL, summary TEXT, remarks TEXT, start DATETIME NOT NULL, end DATETIME, all_day TINYINT(1) NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX (user_id), INDEX(start), INDEX(doctor_id), CONSTRAINT fk_ev_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
q("CREATE TABLE IF NOT EXISTS event_attendees ( event_id INT NOT NULL, user_id INT NOT NULL, added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(event_id,user_id), INDEX(user_id), CONSTRAINT fk_ea_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE, CONSTRAINT fk_ea_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
q("CREATE TABLE IF NOT EXISTS report_status_history ( id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, report_id INT NOT NULL, actor_user_id INT NULL, old_status VARCHAR(40) NULL, new_status VARCHAR(40) NOT NULL, comment TEXT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_rsh_report (report_id), CONSTRAINT fk_rsh_report FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE CASCADE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
q("CREATE TABLE IF NOT EXISTS audit_logs ( id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT NULL, action VARCHAR(120) NOT NULL, entity_type VARCHAR(80) NULL, entity_id INT NULL, details TEXT NULL, ip_address VARCHAR(64) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
q("CREATE TABLE IF NOT EXISTS login_attempts ( id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) NOT NULL, ip_address VARCHAR(64) NOT NULL, was_successful TINYINT(1) NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_login_attempts_email_ip (email, ip_address, created_at) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
echo '</ul><p><strong>Done.</strong> Create your first manager account directly in the database or through your existing user flows. Disable ALLOW_SETUP immediately after use.</p>';
?>
